apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cohort5-ckaprep
  name: cohort5-ckaprep
  namespace: co5website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cohort5-ckaprep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cohort5-ckaprep
    spec:
      containers:
      - name: ctr-web
        image: nginx
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html/
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        ports:
        - containerPort: 8083
          name: http
          protocol: TCP
      - name: ctr-sync
        image: k8s.gcr.io/git-sync:v3.1.6
        volumeMounts:
        - name: html
          mountPath: /tmp/git
        env:
        - name: GIT_SYNC_REPO
          value: https://github.com/kyawzinmyolwin/cohort5website.git
        - name: GIT_SYNC_BRANCH
          value: ckaprep
        - name: GIT_SYNC_DEPTH
          value: "1"
        - name: GIT_SYNC_DEST
          value: "ckaprep"
      volumes:
      - name: html
        emptyDir: {}
      - name: nginx-config-volume
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: svc-ckaprep
  namespace: co5website
spec:
  selector:
    app: cohort5-ckaprep
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
  type: NodePort